skoolit/models/usuario.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

#local imports
from skoolit import db

class Usuario(UserMixin,db.Model):

	__tablename__ = 'usuarios'
	id = db.Column(db.Integer, primary_key=True)
	email = db.Column(db.String, nullable=False)
	papel = db.Column(db.String)
	nome = db.Column(db.String, nullable=False)
	hashSenha = db.Column(db.String, nullable=False)

	__mapper_args__ = {
		'polymorphic_identity':'usuario',
		'polymorphic_on':papel
    }

	def __init__(self, email, papel, nome, senha):
		self.email = email
		self.papel = papel
		self.nome = nome
		self.hashSenha = generate_password_hash(senha)
	
	def validarSenha(self, senha):
		return check_password_hash(self.hashSenha, senha)

	def updateSenha(self, newSenha):
		self.hashSenha = generate_password_hash(newSenha)
		db.session.commit()

	def dbAddUser(self):
		db.session.add(self)
		db.session.commit()
	
	def dbUpdateUser(self, newEmail, newSenha, newNome, newPapel):
		self.email = newEmail
		if (newSenha != None):
			self.updateSenha(newSenha)
		self.nome = newNome
		self.papel = newPapel
		db.session.commit()
	
	def dbUpdateEmail(self, newEmail):
		self.email = newEmail
		db.session.commit()
		
	def dbUpdateNome(self, newNome):
		self.nome = newNome
		db.session.commit()

	def dbDeleteUser(id):
		usuario = Usuario.dbGetUser(id)
		db.session.delete(usuario)
		db.session.commit()

	def dbGetAllUsers():
		return Usuario.query.all()
	
	def dbGetUser(id):
		return Usuario.query.filter_by(id=id).first_or_404()
	
	def dbGetUserNomeEmail(identificador):
		# Retorna o usuário via nome ou email
		userNome = Usuario.query.filter_by(nome=identificador).first()
		userMail = Usuario.query.filter_by(email=identificador).first()
		if (userMail is None and userNome is None):
			return None
		elif userNome is not None:
			return userNome
		else:
			return userMail
	

skoolit/forms/usuarios_forms.py
from flask_wtf import FlaskForm
from wtforms.fields.html5 import EmailField 
from wtforms import (StringField, SubmitField, SelectField, 
PasswordField, ValidationError)

#local imports
from skoolit.models import Usuario
from skoolit.validators import CampoObrigatorio, ValidarEmail, IgualA


class CriarUsuarioForm(FlaskForm):
    email = EmailField("E-mail do usuário: ",
                        validators=[CampoObrigatorio(),ValidarEmail()])
    papel = SelectField("Papel do usuário: ",
                        choices=[('adm', 'Administrador'), 
                                 ('al', 'Aluno'),
                                 ('prof', 'Professor')],
                        validators=[CampoObrigatorio()])
    nome = StringField("Nome de usuário: ", validators=[CampoObrigatorio()])
    senha = PasswordField('Senha', validators=[CampoObrigatorio()])
    senha2 = PasswordField('Confirme a senha', 
                            validators=[CampoObrigatorio(), IgualA('senha')])       
    submit = SubmitField("Criar")

    # Os nomes desses métodos devem ser em inglês para que o WTForms os 
    # reconheça como validadores padrão para os campos, além dos já colocados lá
    def validate_nome(self, nome):
        usuario = Usuario.query.filter_by(nome=nome.data).first()
        if usuario is not None:
            raise ValidationError('Nome de usuário já cadastrado')

    def validate_email(self, email):
        usuario = Usuario.query.filter_by(email=email.data).first()
        if usuario is not None:
            raise ValidationError('Email já cadastrado')


class AtualizarUsuarioForm(FlaskForm):
    email = EmailField("E-mail do usuário: ",
                        validators=[CampoObrigatorio(),ValidarEmail()])
    papel = SelectField("Papel do usuário: ",
                        choices=[('adm', 'Administrador'), 
                                 ('al', 'Aluno'),
                                 ('prof', 'Professor')],
                        validators=[CampoObrigatorio()])
    nome = StringField("Nome de usuário: ", validators=[CampoObrigatorio()])
    senha = PasswordField('Senha', validators=[])
    submit = SubmitField("Atualizar")

class EditarPerfilForm(FlaskForm):
    nome = StringField("Nome: ", validators=[])
    email = EmailField("E-mail: ", validators=[ValidarEmail()])
    submit = SubmitField("Salvar")

skoolit/views/turmas.py
import re
from datetime import datetime
from flask import render_template, redirect, url_for, request, Blueprint, flash
from flask_login import login_required, current_user

#local imports
from skoolit import app
from skoolit.models import Usuario, Professor, Materia, Turma, Postagem, Aluno, Modulo
from skoolit.forms import (CriarTurmaForm, AtualizarTurmaForm, CriarPostForm, EditarPostForm,
						   AdicionarAlunoTurmaForm, AdicionarProfessorTurmaForm,
						   AdicionarTurmaProfessorForm, CriarModuloForm, EditarModuloForm,
						   MatriculaAlunoTurma)

turmas = Blueprint('turmas',__name__, template_folder='templates/turmas')

@turmas.before_request
@login_required
def exigirLogin():
	pass

@turmas.route('/')
def home():
	return render_template('home.html')

def getAluno(idAluno):
	aluno = Aluno.dbGetUser(idAluno)
	return aluno

@turmas.route('/criar', methods=['POST', 'GET'])
def criar():
	form = CriarTurmaForm()
	form.materia_id.choices = Materia.dbGetAllMateria()

	if form.validate_on_submit():
		materia = Materia.dbGetMateria(form.materia_id.data)
		nova_turma = Turma(titulo=form.titulo.data, materia=materia)
		nova_turma.dbAddTurma()
		return redirect(url_for('turmas.listar'))

	return render_template('turmas/criar_turma.html', form=form)

def embed_url(video_url):
        regex = r"(?:https:\/\/)?(?:www\.)?(?:youtube\.com|youtu\.be)\/(?:watch\?v=)?(.+)"
        return re.sub(regex, r"https://www.youtube.com/embed/\1",video_url)

@turmas.route('/listar', methods=['POST', 'GET'])
@turmas.route('/listar/<id>', methods=['POST', 'GET'])
def listar(id=None):
	if id is None:
		turmas = Turma.dbGetAllTurma()
		return render_template('turmas/listar_turmas.html', turmas=turmas)
	else:
		turma = Turma.dbGetTurma(id)
		postagens = Postagem.dbGetPostsByTurma(turma.id)
		modulos = Modulo.dbGetModulosByTurma(turma.id)
		ehProf = turma.ehProfessor(current_user.id)
		return render_template('turmas/detalhes_turma.html', 
							    turma=turma, postagens=postagens, ehProf=ehProf, modulos=modulos, embed_url=embed_url)

@turmas.route('/listar-membros/<id>', methods=['POST', 'GET'])
def listar_membros(id):
	turma = Turma.dbGetTurma(id)
	return render_template('turmas/membros_turma.html', turma=turma, alunos=turma.alunos)

@turmas.route('/listar-prof/<id>', methods=['POST', 'GET'])
def listar_professores(id):
	turma = Turma.dbGetTurma(id)
	return render_template('turmas/professores_turma.html', turma=turma, professores=turma.professores)

@turmas.route('/atualizar/<id>', methods=['POST', 'GET'])
def atualizar(id):
	turma = Turma.dbGetTurma(id)
	form = AtualizarTurmaForm()

	# Monta as opções para escolher matéria, o append e reverse abaixo são
	# para garantir que a matéria atual esteja pré-selecionada para o usuário
	matId = turma.materia_id
	form.materia_id.choices = Materia.dbGetAllMateriaIdNomeExcept(matId)
	materiaatual = Materia.dbGetMateriaIdNome(matId)
	form.materia_id.choices.append(materiaatual)
	form.materia_id.choices.reverse()

	if form.validate_on_submit():
		materia = Materia.dbGetMateria(form.materia_id.data)
		turma.dbUpdateTurma(form.titulo.data, materia)
		return redirect(url_for('turmas.listar'))
	elif request.method == 'GET':
		form.titulo.data = turma.titulo
		form.materia_id.data = turma.materia_id

	return render_template('turmas/atualizar_turma.html', form=form)

@turmas.route('/adicionar-aluno/<id>', methods=['POST', 'GET'])
def adicionar_aluno(id):
	turma = Turma.dbGetTurma(id)
	form = AdicionarAlunoTurmaForm()

	form.aluno_id.choices = Aluno.dbGetAllAlunoIdNome()

	if form.validate_on_submit():
		# Não precisamos validar essa busca, 
		# pois os dados do SelectField eram válidos
		aluno = getAluno(form.aluno_id.data)
		turma.dbAddAluno(aluno)
		return redirect(url_for('turmas.listar_membros', id=turma.id))

	return render_template('turmas/adicionar_aluno_turma.html', form=form, turma=turma)

@turmas.route('/remover-aluno/<id>/<id_aluno>', methods=['POST', 'GET'])
def remover_aluno(id, id_aluno):
	turma = Turma.dbGetTurma(id)
	aluno = getAluno(id_aluno)
	turma.dbDeleteAluno(aluno)
	
	return redirect(url_for('turmas.listar_membros', id=turma.id))

@turmas.route('/adicionar-professor/<id>', methods=['POST', 'GET'])
def adicionar_professor(id):
	if current_user.papel == 'prof':
		prof = Usuario.dbGetUser(id)
		form = AdicionarTurmaProfessorForm()
		form.turma_id.choices = Turma.dbGetAllTurmaIdMateriaTitulo()

		if form.validate_on_submit():
			turma = Turma.dbGetTurma(form.turma_id.data)
			turma.dbAddProfessor(prof)
			return redirect(url_for('home'))

		return render_template('turmas/adicionar_turma_professor.html', form=form, professor=prof)

	else:
		turma = Turma.dbGetTurma(id)
		form = AdicionarProfessorTurmaForm()
		form.professor_id.choices = Professor.dbGetAllProfIdNome()

		if form.validate_on_submit():
			professor = Professor.dbGetUser(form.professor_id.data)
			turma.dbAddProfessor(professor)
			return redirect(url_for('turmas.listar_professores', id=turma.id))

		return render_template('turmas/adicionar_professor_turma.html', form=form, turma=turma)

def get_sugestoes_matricula(turmas): #TODO: melhorar sugestoes
	resposta = []
	for t in  turmas[0:3]:
		resposta.append(t[1])
	return resposta

@turmas.route('/matricula/<id>', methods=['POST', 'GET'])
def matricula(id):
	if current_user.papel == 'al':
		aluno = Usuario.dbGetUser(id)
		turmas = Turma.dbGetAllTurmaIdMateriaTitulo()
		sugestoes = get_sugestoes_matricula(turmas)
		
		form = MatriculaAlunoTurma()
		form.turma_id.choices = turmas
		
		if form.validate_on_submit(): #adiciona aluno na turma
			turma = Turma.dbGetTurma(form.turma_id.data)
			if turma.ehAluno(id):
				mensagem_erro = "Você já está matriculado na turma " + turma.materia.nome + " - " + turma.titulo + "."
				return render_template('turmas/matricula.html', form=form, aluno=aluno, sugestoes = sugestoes, mensagem_erro=mensagem_erro)
			turma.dbAddAluno(aluno)
			return redirect(url_for('home'))
		return render_template('turmas/matricula.html', form=form, aluno=aluno, sugestoes=sugestoes)
		

@turmas.route('/remover-professor/<id>/<id_professor>', methods=['POST', 'GET'])
def remover_professor(id, id_professor):
	turma = Turma.dbGetTurma(id)
	professor = Professor.dbGetUser(id_professor)
	turma.dbDeleteProfessor(professor)
	return redirect(url_for('turmas.listar_professores', id=turma.id))

@turmas.route('/excluir/<id>', methods=['GET'])
def excluir(id):
	Turma.dbDeleteTurma(id)
	return redirect(url_for('turmas.listar'))

@turmas.route('/postar/<id>/<id_prof>', methods=['POST', 'GET'])
def postar(id, id_prof):
	turma = Turma.dbGetTurma(id)
	prof = turma.getProfessor(id_prof)
	data = datetime.today()

	# Só professor/admin pode criar postagens
	if(current_user.papel == 'al'):
		return redirect(url_for('turmas.listar', id=turma.id))

	form = CriarPostForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		link = form.video.data
		novaPostagem = Postagem(titulo=titulo, turma=turma, professorId=prof.id, professor=prof, texto=texto, data=data, video=link)
		novaPostagem.dbAddPost()
		return redirect(url_for('turmas.listar', id=id))
	return render_template('turmas/criar_postagem.html', form=form)

@turmas.route('/editar-post/<id>/<post_id>', methods=['POST', 'GET'])
def editarPostagem(id, post_id):
	turma = Turma.dbGetTurma(id)
	post = Postagem.dbGetPost(post_id)
	
	# Só quem fez a postagem pode editar
	if current_user.id != post.professor_id:
		return redirect(url_for('turmas.listar', id=turma.id))
	
	form = EditarPostForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		link = form.video.data
		post.dbUpdatePost(titulo=titulo, texto=texto, video=link)
		return redirect(url_for('turmas.listar', id=turma.id))
	return render_template('turmas/editar_postagem.html', form=form, post=post)

@turmas.route('/excluir-post/<id>/<post_id>')
def excluirPostagem(id, post_id):
	turma = Turma.dbGetTurma(id)
	post = Postagem.dbGetPost(post_id)

	# Só quem fez a postagem pode deletá-la
	if current_user.id != post.professor_id:
		return redirect(url_for('turmas.listar', id=turma.id))
	
	Postagem.dbDeletePost(post_id)
	return redirect(url_for('turmas.listar', id=turma.id))

@turmas.route('/criar-modulo/<id>', methods=['POST', 'GET'])
def criarModulo(id):
	turma = Turma.dbGetTurma(id)

	# Só professor da turma pode criar módulo
	if not turma.ehProfessor(current_user.id) :
		return redirect(url_for('turmas.listar', id=turma.id))
	
	form = CriarModuloForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		novoModulo = Modulo(titulo=titulo, turma=turma, texto=texto)
		novoModulo.dbAddModulo()
		return redirect(url_for('turmas.listar', id=id))
	return render_template('turmas/criar_modulo.html', form=form)

@turmas.route('/editar-modulo/<id>/<modulo_id>', methods=['POST', 'GET'])
def editarModulo(id, modulo_id):
	turma = Turma.dbGetTurma(id)
	if not turma.ehProfessor(current_user.id):
		return redirect(url_for('turmas.listar', id=turma.id))
	
	modulo = Modulo.dbGetModulo(modulo_id)
	form = EditarModuloForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		modulo.dbUpdateModulo(titulo=titulo, texto=texto)
		return redirect(url_for('turmas.listar', id=turma.id))
	return render_template('turmas/editar_modulo.html', form=form, modulo=modulo)


@turmas.route('/excluir-modulo/<id>/<modulo_id>', methods=['POST', 'GET'])
def excluirModulo(id, modulo_id):
	turma = Turma.dbGetTurma(id)
	if not turma.ehProfessor(current_user.id):
		return redirect(url_for('turmas.listar', id=turma.id))
	
	Modulo.dbDeleteModulo(modulo_id)
	return redirect(url_for('turmas.listar', id=turma.id))

skoolit/views/usuarios.py
from flask import (render_template, redirect, url_for, request, Blueprint, 
flash)
from flask_login import login_required

#local imports
from skoolit import app
from skoolit.forms import CriarUsuarioForm, AtualizarUsuarioForm, EditarPerfilForm
from skoolit.models import Usuario


usuarios = Blueprint('usuarios',__name__, template_folder='templates/usuarios')

# @usuarios.route('/')
# def home():
# 	return render_template('home.html')

@usuarios.before_request
@login_required
def exigirLogin():
	pass

@usuarios.route('/criar', methods=['POST', 'GET'])
def criar():
	form = CriarUsuarioForm()
	if form.validate_on_submit():
		novo_usuario = Usuario(email=form.email.data,
									  papel=form.papel.data,
									  senha=form.senha.data,
									  nome=form.nome.data)
		novo_usuario.dbAddUser()
		return redirect(url_for('usuarios.listar'))

	return render_template('usuarios/criar_usuario.html', form=form)


@usuarios.route('/listar', methods=['POST', 'GET'])
def listar():
	usuarios = Usuario.dbGetAllUsers()
	return render_template('usuarios/listar_usuarios.html', usuarios=usuarios)


@usuarios.route('/atualizar/<id>', methods=['POST', 'GET'])
def atualizar(id):
	usuario = Usuario.dbGetUser(id)
	form = AtualizarUsuarioForm()
	if form.validate_on_submit():
		usuario.dbUpdateUser(newEmail=form.email.data,newSenha=form.senha.data, 
							 newNome=form.nome.data, newPapel=form.papel.data)
		return redirect(url_for('usuarios.listar'))
	elif request.method == 'GET':
		form.email.data = usuario.email
		form.papel.data = usuario.papel
		form.nome.data = usuario.nome

	return render_template('usuarios/atualizar_usuario.html', form=form)


@usuarios.route('/excluir/<id>', methods=['GET'])
def excluir(id):
	Usuario.dbDeleteUser(id)
	return redirect(url_for('usuarios.listar'))

@usuarios.route('/perfil/<id>', methods=['GET'])
def perfil(id):
	usuario = Usuario.dbGetUser(id)
	return render_template('usuarios/perfil.html', usuario=usuario)

@usuarios.route('/editar_perfil/<id>', methods=['GET', 'POST'])
def editar_perfil(id):
	usuario = Usuario.dbGetUser(id)
	form = EditarPerfilForm()
	
	if form.validate_on_submit(): 
		if form.email.data != None and form.email.data != '':
			usuario.dbUpdateEmail(form.email.data)
		if form.nome.data != None and form.nome.data != '':
			usuario.dbUpdateNome(form.nome.data)
		return redirect(url_for('usuarios.perfil',id=id))

	return render_template('usuarios/editar_perfil.html', usuario=usuario, form = form)

skoolit/templates/usuarios/atualizar_usuario.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='usuarios/form_usuario.css') }}">
{% endblock %}


{% block title %}Atualizar usuário{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Atualizar usuário</h1>
	</div>

	<div class="card form-usuario">
		<div class="card-body">
			<form method="POST" novalidate>
				<div class="d-flex flex-wrap">
					<div class="col-5">
						{{form.hidden_tag()}}
						{{form.nome.label(class="form-label")}} {{form.nome(class="form-control", size=40)}} 
						{% for error in form.nome.errors %}
						<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>
					<div class="col-5 ml-2">
						{{form.email.label(class="form-label")}} {{form.email(class="form-control", size=40)}}
						{% for error in form.email.errors %}
							<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>
				</div>

				<br>
				
				<div class="d-flex flex-wrap">
					<div class="col-5">
						{{form.senha.label(class="form-label")}} {{form.senha(class="form-control", size=40)}}
						{% for error in form.senha.errors %}
							<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>
					<div class="col-5 ml-2">
						{{form.papel.label(class="form-label")}} {{form.papel(class="form-control")}}
					</div>
				</div>
				<br>
				<div class="d-flex col-5">
					{{form.submit(class="btn")}}
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

skoolit/templates/usuarios/criar_usuario.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='usuarios/form_usuario.css') }}">
{% endblock %}


{% block title %}Criar usuário{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Criar usuário</h1>
	</div>

	<div class="card form-usuario">
		<div class="card-body">
			<form method="POST" novalidate>
				<div class="d-flex flex-wrap">
					<div class="col-5">
						{{form.hidden_tag()}}
						{{form.nome.label(class="form-label")}} {{form.nome(class="form-control", size=40)}} 
						{% for error in form.nome.errors %}
							<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>					
					<div class="col-5 ml-2">
						{{form.email.label(class="form-label")}} {{form.email(class="form-control", size=40)}}
						{% for error in form.email.errors %}
							<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>
				</div>
				
				<br>

				<div class="d-flex flex-wrap">
					<div class="col-5">
						{{form.senha.label(class="form-label")}} {{form.senha(class="form-control", size=40)}}
						{% for error in form.senha.errors %}
							<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>					
					<div class="col-5 ml-2">
						{{form.senha2.label(class="form-label")}} {{form.senha2(class="form-control", size=40)}}
						{% for error in form.senha2.errors %}
							<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>
				</div>
		
				<br>
				
				<div class="col-5">
					{{form.papel.label(class="form-label")}} {{form.papel(class="form-control")}}
				</div>
				
				<br>

				<div class="d-flex col-5">
					{{form.submit(class="btn")}}
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

skoolit/templates/usuarios/home_aluno.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/listar_turmas.css') }}">
{% endblock %}

{% block title %}Skoolit - Home{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Suas turmas</h1>

		<div class="mt-2">		
			<a href="{{url_for('turmas.matricula', id=current_user.id)}}"
				class="btn" role="button">
				Matricule-se
			</a>
		</div>
	</div>

	<div class="row">
		{% for turma in turmas %}
			<div class="card turma">
				<div class="badge">
					{{turma.titulo[:3]|upper}}
				</div>
				<div class="card-body">
					<h5 class="card-title text-center"> 
						<a class="turma-nome" href="{{url_for('turmas.listar', id=turma.id)}}">{{turma.materia.nome}}</a>
					</h5>
					<div class="text-center">
						<a href="{{url_for('turmas.listar', id=turma.id)}}" class="card-link">Info</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	{% if turmas|length == 0  %}
		<p>Você não está matriculado em nenhuma turma.</p>
	{% endif %}
</div>
{% endblock %}

skoolit/templates/usuarios/home_prof.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/listar_turmas.css') }}">
{% endblock %}

{% block title %}Skoolit - Home{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Suas turmas</h1>

		<div class="mt-2">		
			<a href="{{url_for('turmas.adicionar_professor', id=current_user.id)}}"
				class="btn" role="button">
				Inscrever-se
			</a>
		</div>
	</div>

	<div class="row">
		{% for turma in turmas %}
			<div class="card turma">
				<div class="badge">
					{{turma.titulo[:3]|upper}}
				</div>
				<div class="card-body">
					<h5 class="card-title text-center"> 
						<a class="turma-nome" href="{{url_for('turmas.listar', id=turma.id)}}">{{turma.materia.nome}}</a>
					</h5>
					<div class="text-center">
						<a href="{{url_for('turmas.listar', id=turma.id)}}" class="card-link">Info</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	{% if turmas|length == 0  %}
		<p>Você não leciona em nenhuma turma.</p>
	{% endif %}
</div>
{% endblock %}

skoolit/templates/usuarios/listar_usuarios.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='usuarios/listar_usuarios.css') }}">
{% endblock %}

{% block title %}Listar usuários{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Usuários</h1>

		<div>
				<a href="{{url_for('usuarios.criar')}}"
					class="btn" role="button">
					Novo usuário
				</a>
		</div>
	</div>
	
	<div class="card usuarios pl-5 pr-5 pt-5 pb-2">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">ID</th>
					<th scope="col">Nome</th>
					<th scope="col">Email</th>
					<th scope="col">Papel</th>
					<th scope="col">Editar</th>
					<th scope="col">Excluir</th>
				</tr>
			</thead>
			<tbody>
				{% for usuario in usuarios %}
					<tr>
						<th scope="row">{{usuario.id}}</th>
						<td>{{usuario.nome}}</td>
						<td>{{usuario.email}}</td>
						{% if usuario.papel == "al" %}
							<td>Aluno</td>
						{% elif usuario.papel == "prof" %}
							<td>Professor</td>	
						{% elif usuario.papel == "adm" %}
							<td>Admin</td>	
						{% endif %}
						<td><a href="{{url_for('usuarios.atualizar', id=usuario.id)}}">Editar</a></td>
						{% if current_user.id != usuario.id %}
							<td> <a href="{{url_for('usuarios.excluir', id=usuario.id)}}">Excluir</a></td>
						{% endif %}
					</tr>
				{%endfor %}
			</tbody>
		</table>

		{% if usuarios|length == 0  %}
			<p>Não existem tarefas criadas.</p>
		{% endif %}
	</div>
</div>
{% endblock %}
	

skoolit/templates/usuarios/perfil.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block title %}{{ usuario.nome }} - Perfil{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
        <h1 class="bold">Perfil</h1>	        
    </div>

    <div class="row">
        <div class="column col-5">
            <div class="card modulos-turma">
                <div class="card-body">
                    
                    <p> <b>Nome: </b> {{usuario.nome}}</p>
                    <p><b>email: </b> {{usuario.email}}</p> 
                    <p><b>ID: </b> {{usuario.id}}</p>
                    <p> <b>Papel: </b>
                        {% if usuario.papel == 'al' %} Aluno {% endif %}
                        {% if usuario.papel == 'prof' %} Professor {% endif %}
                        {% if usuario.papel == 'adm' %} Administrador {% endif %} 
                    </p> 
                    <br>
                    <div class="mt-2">		
                        <a href="{{url_for('usuarios.editar_perfil', id=current_user.id)}}"
                            class="btn" role="button">
                            Editar Informações
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
{% endblock %}