skoolit/models/turma.py
#local imports
from skoolit import db
# from skoolit.models import Aluno

turma_alunos = db.Table('turma_alunos',
    db.Column('turma_id', db.Integer, db.ForeignKey('turmas.id'), primary_key=True),
    db.Column('aluno_id', db.Integer, db.ForeignKey('usuarios.id'), primary_key=True)
)

turma_prof = db.Table('turma_professor',
    db.Column('turma_id', db.Integer, db.ForeignKey('turmas.id'), primary_key=True),
    db.Column('prof_id', db.Integer, db.ForeignKey('usuarios.id'), primary_key=True)
)

class Turma(db.Model):

	__tablename__ = 'turmas'

	id = db.Column(db.Integer, primary_key=True)
	titulo = db.Column(db.String, nullable=False)
	materia_id = db.Column(db.Integer, db.ForeignKey('materias.id'), nullable=False)
	materia = db.relationship('Materia', back_populates='turmas')

	professores = db.relationship('Professor', secondary='turma_professor', lazy='subquery',
        backref=db.backref('turmas', lazy=True))

	postagens = db.relationship('Postagem', backref='turma')
	modulos = db.relationship('Modulo', backref='turma')

	alunos = db.relationship('Aluno', secondary='turma_alunos', lazy='subquery',
        backref=db.backref('turmas', lazy=True))

	def __init__(self, titulo, materia):
		self.titulo = titulo
		self.materia_id = materia.id
		self.materia = materia
	
	def dbAddTurma(self):
		db.session.add(self)
		db.session.commit()
	
	def dbUpdateTurma(self, newTitulo, newMateria):
		self.titulo = newTitulo
		self.materia_id = newMateria.id
		self.materia = newMateria
		db.session.commit()
	
	def dbDeleteTurma(id):
		turma = Turma.dbGetTurma(id)
		db.session.delete(turma)
		db.session.commit()

	def dbGetAllTurma():
		return Turma.query.all()
	
	def dbGetTurma(id):
		return Turma.query.filter_by(id=id).first_or_404()

	def dbAddAluno(self, aluno):
		self.alunos.append(aluno)
		db.session.commit()

	def dbDeleteAluno(self, aluno):
		self.alunos.remove(aluno)
		db.session.commit()
	
	def dbAddProfessor(self, professor):
		self.professores.append(professor)
		db.session.commit()

	def dbDeleteProfessor(self, professor):
		self.professores.remove(professor)
		db.session.commit()
	
	def ehProfessor(self, id):
		# Retorna True se o professor com id 'id' é professor da turma
		for prof in self.professores:
			if str(prof.id) == str(id):
				return True
		return False

	def ehAluno(self, id):
		# Retorna True se o aluno com id 'id' é aluno da turma
		for aluno in self.alunos:
			if str(aluno.id) == str(id):
				return True
		return False

	def dbGetAllTurmaIdMateriaTitulo():
		turmas = Turma.query.all()
		lista = []
		for turma in turmas:
			turmaId = turma.id
			turmaMateria = turma.materia.nome
			turmaTitulo = turma.titulo
			label = str(turmaMateria) + " - " + str(turmaTitulo)
			choice = (turmaId, label)
			lista.append(choice)
		return lista
	
	def getProfessor(self, id):
		for prof in self.professores:
			if int(prof.id) == int(id):
				return prof
		return None

	def dbGetPost(self, id):
		self.postagens.query.filter_by(id=id).first_or_404()

skoolit/forms/turmas_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField, TextAreaField
from wtforms.validators import DataRequired

#local imports
from skoolit.validators import CampoObrigatorio
class CriarTurmaForm(FlaskForm):
    titulo = StringField("Título da turma: ", validators=[CampoObrigatorio()])
    materia_id = SelectField("Matéria: ", validators=[CampoObrigatorio()])
    submit = SubmitField("Criar")

class AtualizarTurmaForm(FlaskForm):
    titulo = StringField("Título da turma: ", validators=[CampoObrigatorio()])
    materia_id = SelectField("Matéria: ", validators=[CampoObrigatorio()])
    submit = SubmitField("Atualizar")

class CriarPostForm(FlaskForm):
    titulo = StringField("Título da Postagem: ", validators=[CampoObrigatorio()])
    texto = TextAreaField("Conteúdo da Postagem: ", validators=[CampoObrigatorio()])
    video = StringField("Link de Vídeo (Opcional): ", filters=[lambda x: x or None])
    submit = SubmitField("Postar")

class EditarPostForm(FlaskForm):
    titulo = StringField("Título da Postagem: ", validators=[CampoObrigatorio()])
    texto = TextAreaField("Conteúdo da Postagem: ", validators=[CampoObrigatorio()])
    video = StringField("Link de Vídeo (Opcional): ", filters=[lambda x: x or None])
    submit = SubmitField("Atualizar")

class CriarModuloForm(FlaskForm):
    titulo = StringField("Título do Módulo: ", validators=[CampoObrigatorio()])
    texto = TextAreaField("Conteúdo do Módulo: ", validators=[CampoObrigatorio()])
    submit = SubmitField("Criar")

class EditarModuloForm(FlaskForm):
    titulo = StringField("Título do Módulo: ", validators=[CampoObrigatorio()])
    texto = TextAreaField("Conteúdo do Módulo: ", validators=[CampoObrigatorio()])
    submit = SubmitField("Atualizar")

class AdicionarAlunoTurmaForm(FlaskForm):
	aluno_id = SelectField("Aluno: ", validators=[CampoObrigatorio()])
	submit = SubmitField("Adicionar")

class AdicionarProfessorTurmaForm(FlaskForm):
    professor_id = SelectField("Professor: ", validators=[CampoObrigatorio()])
    submit = SubmitField("Adicionar")

class AdicionarTurmaProfessorForm(FlaskForm):
    turma_id = SelectField("Materia: ", validators=[CampoObrigatorio()])
    submit = SubmitField("Inscrever")

class MatriculaAlunoTurma(FlaskForm):
    turma_id = SelectField("Materia: ", validators=[CampoObrigatorio()])
    submit = SubmitField("Matricular")

skoolit/views/turmas.py
import re
from datetime import datetime
from flask import render_template, redirect, url_for, request, Blueprint, flash
from flask_login import login_required, current_user

#local imports
from skoolit import app
from skoolit.models import Usuario, Professor, Materia, Turma, Postagem, Aluno, Modulo
from skoolit.forms import (CriarTurmaForm, AtualizarTurmaForm, CriarPostForm, EditarPostForm,
						   AdicionarAlunoTurmaForm, AdicionarProfessorTurmaForm,
						   AdicionarTurmaProfessorForm, CriarModuloForm, EditarModuloForm,
						   MatriculaAlunoTurma)

turmas = Blueprint('turmas',__name__, template_folder='templates/turmas')

@turmas.before_request
@login_required
def exigirLogin():
	pass

@turmas.route('/')
def home():
	return render_template('home.html')

def getAluno(idAluno):
	aluno = Aluno.dbGetUser(idAluno)
	return aluno

@turmas.route('/criar', methods=['POST', 'GET'])
def criar():
	form = CriarTurmaForm()
	form.materia_id.choices = Materia.dbGetAllMateria()

	if form.validate_on_submit():
		materia = Materia.dbGetMateria(form.materia_id.data)
		nova_turma = Turma(titulo=form.titulo.data, materia=materia)
		nova_turma.dbAddTurma()
		return redirect(url_for('turmas.listar'))

	return render_template('turmas/criar_turma.html', form=form)

def embed_url(video_url):
        regex = r"(?:https:\/\/)?(?:www\.)?(?:youtube\.com|youtu\.be)\/(?:watch\?v=)?(.+)"
        return re.sub(regex, r"https://www.youtube.com/embed/\1",video_url)

@turmas.route('/listar', methods=['POST', 'GET'])
@turmas.route('/listar/<id>', methods=['POST', 'GET'])
def listar(id=None):
	if id is None:
		turmas = Turma.dbGetAllTurma()
		return render_template('turmas/listar_turmas.html', turmas=turmas)
	else:
		turma = Turma.dbGetTurma(id)
		postagens = Postagem.dbGetPostsByTurma(turma.id)
		modulos = Modulo.dbGetModulosByTurma(turma.id)
		ehProf = turma.ehProfessor(current_user.id)
		return render_template('turmas/detalhes_turma.html', 
							    turma=turma, postagens=postagens, ehProf=ehProf, modulos=modulos, embed_url=embed_url)

@turmas.route('/listar-membros/<id>', methods=['POST', 'GET'])
def listar_membros(id):
	turma = Turma.dbGetTurma(id)
	return render_template('turmas/membros_turma.html', turma=turma, alunos=turma.alunos)

@turmas.route('/listar-prof/<id>', methods=['POST', 'GET'])
def listar_professores(id):
	turma = Turma.dbGetTurma(id)
	return render_template('turmas/professores_turma.html', turma=turma, professores=turma.professores)

@turmas.route('/atualizar/<id>', methods=['POST', 'GET'])
def atualizar(id):
	turma = Turma.dbGetTurma(id)
	form = AtualizarTurmaForm()

	# Monta as opções para escolher matéria, o append e reverse abaixo são
	# para garantir que a matéria atual esteja pré-selecionada para o usuário
	matId = turma.materia_id
	form.materia_id.choices = Materia.dbGetAllMateriaIdNomeExcept(matId)
	materiaatual = Materia.dbGetMateriaIdNome(matId)
	form.materia_id.choices.append(materiaatual)
	form.materia_id.choices.reverse()

	if form.validate_on_submit():
		materia = Materia.dbGetMateria(form.materia_id.data)
		turma.dbUpdateTurma(form.titulo.data, materia)
		return redirect(url_for('turmas.listar'))
	elif request.method == 'GET':
		form.titulo.data = turma.titulo
		form.materia_id.data = turma.materia_id

	return render_template('turmas/atualizar_turma.html', form=form)

@turmas.route('/adicionar-aluno/<id>', methods=['POST', 'GET'])
def adicionar_aluno(id):
	turma = Turma.dbGetTurma(id)
	form = AdicionarAlunoTurmaForm()

	form.aluno_id.choices = Aluno.dbGetAllAlunoIdNome()

	if form.validate_on_submit():
		# Não precisamos validar essa busca, 
		# pois os dados do SelectField eram válidos
		aluno = getAluno(form.aluno_id.data)
		turma.dbAddAluno(aluno)
		return redirect(url_for('turmas.listar_membros', id=turma.id))

	return render_template('turmas/adicionar_aluno_turma.html', form=form, turma=turma)

@turmas.route('/remover-aluno/<id>/<id_aluno>', methods=['POST', 'GET'])
def remover_aluno(id, id_aluno):
	turma = Turma.dbGetTurma(id)
	aluno = getAluno(id_aluno)
	turma.dbDeleteAluno(aluno)
	
	return redirect(url_for('turmas.listar_membros', id=turma.id))

@turmas.route('/adicionar-professor/<id>', methods=['POST', 'GET'])
def adicionar_professor(id):
	if current_user.papel == 'prof':
		prof = Usuario.dbGetUser(id)
		form = AdicionarTurmaProfessorForm()
		form.turma_id.choices = Turma.dbGetAllTurmaIdMateriaTitulo()

		if form.validate_on_submit():
			turma = Turma.dbGetTurma(form.turma_id.data)
			turma.dbAddProfessor(prof)
			return redirect(url_for('home'))

		return render_template('turmas/adicionar_turma_professor.html', form=form, professor=prof)

	else:
		turma = Turma.dbGetTurma(id)
		form = AdicionarProfessorTurmaForm()
		form.professor_id.choices = Professor.dbGetAllProfIdNome()

		if form.validate_on_submit():
			professor = Professor.dbGetUser(form.professor_id.data)
			turma.dbAddProfessor(professor)
			return redirect(url_for('turmas.listar_professores', id=turma.id))

		return render_template('turmas/adicionar_professor_turma.html', form=form, turma=turma)

def get_sugestoes_matricula(turmas): #TODO: melhorar sugestoes
	resposta = []
	for t in  turmas[0:3]:
		resposta.append(t[1])
	return resposta

@turmas.route('/matricula/<id>', methods=['POST', 'GET'])
def matricula(id):
	if current_user.papel == 'al':
		aluno = Usuario.dbGetUser(id)
		turmas = Turma.dbGetAllTurmaIdMateriaTitulo()
		sugestoes = get_sugestoes_matricula(turmas)
		
		form = MatriculaAlunoTurma()
		form.turma_id.choices = turmas
		
		if form.validate_on_submit(): #adiciona aluno na turma
			turma = Turma.dbGetTurma(form.turma_id.data)
			if turma.ehAluno(id):
				mensagem_erro = "Você já está matriculado na turma " + turma.materia.nome + " - " + turma.titulo + "."
				return render_template('turmas/matricula.html', form=form, aluno=aluno, sugestoes = sugestoes, mensagem_erro=mensagem_erro)
			turma.dbAddAluno(aluno)
			return redirect(url_for('home'))
		return render_template('turmas/matricula.html', form=form, aluno=aluno, sugestoes=sugestoes)
		

@turmas.route('/remover-professor/<id>/<id_professor>', methods=['POST', 'GET'])
def remover_professor(id, id_professor):
	turma = Turma.dbGetTurma(id)
	professor = Professor.dbGetUser(id_professor)
	turma.dbDeleteProfessor(professor)
	return redirect(url_for('turmas.listar_professores', id=turma.id))

@turmas.route('/excluir/<id>', methods=['GET'])
def excluir(id):
	Turma.dbDeleteTurma(id)
	return redirect(url_for('turmas.listar'))

@turmas.route('/postar/<id>/<id_prof>', methods=['POST', 'GET'])
def postar(id, id_prof):
	turma = Turma.dbGetTurma(id)
	prof = turma.getProfessor(id_prof)
	data = datetime.today()

	# Só professor/admin pode criar postagens
	if(current_user.papel == 'al'):
		return redirect(url_for('turmas.listar', id=turma.id))

	form = CriarPostForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		link = form.video.data
		novaPostagem = Postagem(titulo=titulo, turma=turma, professorId=prof.id, professor=prof, texto=texto, data=data, video=link)
		novaPostagem.dbAddPost()
		return redirect(url_for('turmas.listar', id=id))
	return render_template('turmas/criar_postagem.html', form=form)

@turmas.route('/editar-post/<id>/<post_id>', methods=['POST', 'GET'])
def editarPostagem(id, post_id):
	turma = Turma.dbGetTurma(id)
	post = Postagem.dbGetPost(post_id)
	
	# Só quem fez a postagem pode editar
	if current_user.id != post.professor_id:
		return redirect(url_for('turmas.listar', id=turma.id))
	
	form = EditarPostForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		link = form.video.data
		post.dbUpdatePost(titulo=titulo, texto=texto, video=link)
		return redirect(url_for('turmas.listar', id=turma.id))
	return render_template('turmas/editar_postagem.html', form=form, post=post)

@turmas.route('/excluir-post/<id>/<post_id>')
def excluirPostagem(id, post_id):
	turma = Turma.dbGetTurma(id)
	post = Postagem.dbGetPost(post_id)

	# Só quem fez a postagem pode deletá-la
	if current_user.id != post.professor_id:
		return redirect(url_for('turmas.listar', id=turma.id))
	
	Postagem.dbDeletePost(post_id)
	return redirect(url_for('turmas.listar', id=turma.id))

@turmas.route('/criar-modulo/<id>', methods=['POST', 'GET'])
def criarModulo(id):
	turma = Turma.dbGetTurma(id)

	# Só professor da turma pode criar módulo
	if not turma.ehProfessor(current_user.id) :
		return redirect(url_for('turmas.listar', id=turma.id))
	
	form = CriarModuloForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		novoModulo = Modulo(titulo=titulo, turma=turma, texto=texto)
		novoModulo.dbAddModulo()
		return redirect(url_for('turmas.listar', id=id))
	return render_template('turmas/criar_modulo.html', form=form)

@turmas.route('/editar-modulo/<id>/<modulo_id>', methods=['POST', 'GET'])
def editarModulo(id, modulo_id):
	turma = Turma.dbGetTurma(id)
	if not turma.ehProfessor(current_user.id):
		return redirect(url_for('turmas.listar', id=turma.id))
	
	modulo = Modulo.dbGetModulo(modulo_id)
	form = EditarModuloForm()

	if form.validate_on_submit():
		titulo = form.titulo.data
		texto = form.texto.data
		modulo.dbUpdateModulo(titulo=titulo, texto=texto)
		return redirect(url_for('turmas.listar', id=turma.id))
	return render_template('turmas/editar_modulo.html', form=form, modulo=modulo)


@turmas.route('/excluir-modulo/<id>/<modulo_id>', methods=['POST', 'GET'])
def excluirModulo(id, modulo_id):
	turma = Turma.dbGetTurma(id)
	if not turma.ehProfessor(current_user.id):
		return redirect(url_for('turmas.listar', id=turma.id))
	
	Modulo.dbDeleteModulo(modulo_id)
	return redirect(url_for('turmas.listar', id=turma.id))

skoolit/templates/turmas/adicionar_aluno_turma.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/criar_turma.css') }}">
{% endblock %}

{% block title %}{{ turma.titulo }} - Adicionar aluno{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">{{ turma.titulo }} - Adicionar aluno</h1>
	</div>

	<form class="form-turma" method="POST">

		<div class="d-flex flex-wrap justify-content-start align-items-start">
			<div class="col-5 ml-2">
				{{form.hidden_tag()}}
				{{form.aluno_id.label(class="form-label")}} 
				{{form.aluno_id(class="form-control")}}
			</div>
		</div>
		<br>
		<div class="d-flex">
			<div class="col-5 mr-auto">
				{{form.submit(class="btn")}}
			</div>
		</div>
	
	</form>

</div>

{% endblock %}

skoolit/templates/turmas/adicionar_professor_turma.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/criar_turma.css') }}">
{% endblock %}

{% block title %}{{ turma.titulo }} - Adicionar professor{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">{{ turma.titulo }} - Adicionar professor</h1>
	</div>

	<form class="form-turma" method="POST">

		<div class="d-flex flex-wrap justify-content-start align-items-start">
			<div class="col-5 ml-2">
				{{form.hidden_tag()}}
				{{form.professor_id.label(class="form-label")}} 
				{{form.professor_id(class="form-control")}}
			</div>
		</div>
		<br>
		<div class="d-flex">
			<div class="col-5 mr-auto">
				{{form.submit(class="btn")}}
			</div>
		</div>
	
	</form>

</div>

{% endblock %}

skoolit/templates/turmas/adicionar_turma_professor.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/criar_turma.css') }}">
{% endblock %}

{% block title %}{{ professor.nome }} - Inscrever-se{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">{{ professor.nome }} - Inscrever-se</h1>
	</div>

	<form class="form-turma" method="POST">

		<div class="d-flex flex-wrap justify-content-start align-items-start">
			<div class="col-5 ml-2">
				{{form.hidden_tag()}}
				{{form.turma_id.label(class="form-label")}} 
				{{form.turma_id(class="form-control")}}
			</div>
		</div>
		<br>
		<div class="d-flex">
			<div class="col-5 mr-auto">
				{{form.submit(class="btn")}}
			</div>
		</div>
	
	</form>

</div>

{% endblock %}

skoolit/templates/turmas/atualizar_turma.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/criar_turma.css') }}">
{% endblock %}

{% block title %}Atualizar turma{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Atualizar turma</h1>
	</div>

	<form class="form-turma" method="POST">
		<div class="d-flex">
			<div class="col-5 mr-auto">
				{{form.hidden_tag()}}
				{{form.titulo.label(class="form-label")}}
				{{form.titulo(class="form-control", size=40)}}
				<br>
			</div>
		</div>

		<div class="d-flex flex-wrap justify-content-start align-items-start">
			<div class="col-5">
				{{form.materia_id.label(class="form-label")}} 
				{{form.materia_id(class="form-control")}}	
				
			</div>
		</div>
		<br>
		<div class="d-flex">
			<div class="col-5 mr-auto">
				{{form.submit(class="btn")}}
			</div>
		</div>
	
	</form>

</div>

{% endblock %}

skoolit/templates/turmas/detalhes_turma.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/detalhes_turma.css') }}">
{% endblock %}

{% block title %}{{turma.materia.nome}}{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">{{turma.materia.nome}} - {{turma.titulo}} </h1>

		<div class="mt-2">
			<a href="{{url_for('turmas.listar_professores', id=turma.id)}}"
			class="btn  mr-2" role="button">
				Professores
			</a>
			<a href="{{url_for('turmas.listar_membros', id=turma.id)}}"
			class="btn  mr-2" role="button">
				Membros
			</a>
			{% if current_user.papel == "adm" %}
			<a href="{{url_for('turmas.atualizar', id=turma.id)}}"
			class="btn  ml-2" role="button">
				Editar
			</a>
			{% endif %}
			{% if current_user.papel == "adm" %}
			<a href="{{url_for('turmas.excluir', id=turma.id)}}"
			class="btn ml-2" role="button">
				Excluir
			</a>
			{% endif %}
			{% if ehProf %}
			<a href="{{url_for('turmas.postar', id=turma.id, id_prof=current_user.id)}}"
			class="btn ml-2" role="button">
				Postar
			</a>
			<a href="{{url_for('turmas.criarModulo', id=turma.id)}}"
			class="btn ml-2" role="button">
				Criar Módulo
			</a>
			{% endif %}
		</div>
	</div>
	
	<div class="row">
		<div class="column col-5">
			{% for modulo in modulos %}
			<div class="card modulos-turma">
				<div class="card-body">
					<h5 class="bold" class="card-title"> {{modulo.titulo}} </h5>
					<p class="card-text" style="white-space: pre-line">{{modulo.texto}}</p>
					{% if ehProf %}
					<a href="{{url_for('turmas.editarModulo', id=turma.id, modulo_id=modulo.id)}}" class="btn  mr-2" role="button">
						Editar
					</a>
					<a href="{{url_for('turmas.excluirModulo', id=turma.id, modulo_id=modulo.id)}}" class="btn  mr-2" role="button">
						Excluir
					</a>
					{% endif %}
				</div>
			</div>
			{% endfor %}	
		</div>

		<div class="column card card-postagens col-6 offset-1">
			<div class="card-body">
				<h5 class="bold" class="card-title mb-4"> Postagens</h5>
				{% for post in postagens %}
				<div class="card card-postagem mx-auto">
					<div class="card-body">
						<div class="data float-right">
							<p >{{post.data.strftime('%d/%m/%Y, %H:%M')}}</p>
						</div>
						<div class="perfil-postagem mb-3">
							<div class="perfil-circulo rounded-circle text-center">
								<!-- Nome do post é o professor da turma. Talvez seja interessante
								armazenar isso no post em si. -->
								<b>{{ post.professor.nome[0:2].upper() }}</b>
							</div>
							<p class="autor-postagem card-text ml-3"><b>{{ post.professor.nome | capitalize}}</b></p>
						</div>
						<p class="card-text ml-2"><b>{{post.titulo}}</b></p>
						<p class="card-text" style="white-space: pre-line">{{post.texto}}</p>
						{% if post.video != None %}
						<iframe width="450" height="315" src="{{embed_url(post.video)}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
						{% endif %}
						{% if ehProf and current_user.id == post.professor_id %}
						<a href="{{url_for('turmas.editarPostagem', id=turma.id, post_id=post.id)}}" class="btn  mr-2" role="button">
							Editar
						</a>
						<a href="{{url_for('turmas.excluirPostagem', id=turma.id, post_id=post.id)}}" class="btn  mr-2" role="button">
							Excluir
						</a>
						{% endif %}
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

{% endblock %}

skoolit/templates/turmas/listar_turmas.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='turmas/listar_turmas.css') }}">
{% endblock %}

{% block title %}Listar turmas{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Turmas</h1>

		<div class="mt-2">		
			<a href="{{url_for('turmas.criar')}}"
				class="btn" role="button">
				Nova turma
			</a>
		</div>
	</div>

	<div class="row">
		{% for turma in turmas %}
			<div class="card turma">
				<div class="badge">
					{{turma.titulo[:3]|upper}}
				</div>
				<div class="card-body">
					<h5 class="card-title text-center"> 
						<a class="turma-nome" href="{{url_for('turmas.listar', id=turma.id)}}">{{turma.materia.nome}}</a>
					</h5>
					<div class="text-center">
						<a href="{{url_for('turmas.atualizar', id=turma.id)}}" class="card-link">Editar</a>
						<a href="{{url_for('turmas.excluir', id=turma.id)}}" class="card-link">Excluir</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	{% if turmas|length == 0  %}
		<p>Não existem turmas criadas.</p>
	{% endif %}
</div>
{% endblock %}

skoolit/templates/turmas/professores_turma.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='usuarios/listar_usuarios.css') }}">
{% endblock %}

{% block title %}Listar professores{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">{{ turma.titulo }} - Professores da turma</h1>

		<div>
			{% if current_user.papel == "adm" %}
				<a href="{{url_for('turmas.adicionar_professor', id=turma.id)}}"
					class="btn" role="button">
					Adicionar professor
				</a>
			{% endif %}
		</div>
	</div>
	
	<div class="card usuarios pl-5 pr-5 pt-5 pb-2">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">ID</th>
					<th scope="col">Professor</th>
					<th scope="col">Email</th>
					{% if current_user.papel == "adm" %}
					<th scope="col">Ações</th>
					{% endif %}
				</tr>
			</thead>
			<tbody>
				{% for professor in professores %}
					<tr>
						<th scope="row">{{professor.id}}</th>
						<td>{{professor.nome}}</td>
						<td>{{professor.email}}</td>
						{% if current_user.papel == "adm" %}
						<td> <a href="{{url_for('turmas.remover_professor', id=turma.id, id_professor=professor.id)}}">Remover</a></td>
						{% endif %}
					</tr>
				{%endfor %}
			</tbody>
		</table>

	</div>
</div>
{% endblock %}
	