skoolit/models/materia.py
#local imports
from skoolit import db

class Materia(db.Model):

	__tablename__ = 'materias'

	id = db.Column(db.Integer, primary_key=True)
	nome = db.Column(db.String, nullable=False)
	turmas = db.relationship('Turma', back_populates='materia')

	def __init__(self, nome):
		self.nome = nome

	def dbAddMateria(self):
		db.session.add(self)
		db.session.commit()

	def dbUpdateMateria(self, newNome):
		self.nome = newNome
		db.session.commit()

	def dbDeleteMateria(id):
		materia = Materia.dbGetMateria(id)
		db.session.delete(materia)
		db.session.commit()

	def dbGetAllMateria():
		return Materia.query.with_entities(Materia.id,Materia.nome).all()
	
	def dbGetAllMateriaIdNomeExcept(id):
		return Materia.query.with_entities(Materia.id,Materia.nome) \
					.filter(Materia.id != id) \
					.all()
	
	def dbGetMateria(id):
		return Materia.query.filter(Materia.id == id).first()
	
	def dbGetMateriaIdNome(id):
		return Materia.query.with_entities(Materia.id,Materia.nome) \
					.filter(Materia.id == id) \
					.first()

skoolit/forms/materias_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired

#local imports
from skoolit.validators import CampoObrigatorio

class CriarMateriaForm(FlaskForm):
    nome = StringField("Nome da matéria: ", validators=[DataRequired()])
    submit = SubmitField("Criar")

class AtualizarMateriaForm(FlaskForm):
    nome = StringField("Nome da matéria: ", validators=[DataRequired()])
    submit = SubmitField("Atualizar")

skoolit/views/materias.py
from flask import render_template, redirect, url_for, request, Blueprint, flash
from flask_login import login_required

#local imports
from skoolit import app
from skoolit.models import Materia
from skoolit.forms import CriarMateriaForm, AtualizarMateriaForm 

materias = Blueprint('materias',__name__, template_folder='templates/materias')


@materias.before_request
@login_required
def exigirLogin():
	pass

@materias.route('/')
def home():
	return render_template('home.html')


@materias.route('/criar', methods=['POST', 'GET'])
def criar():
	form = CriarMateriaForm()

	if form.validate_on_submit():
		nova_materia = Materia(form.nome.data)
		nova_materia.dbAddMateria()
		return redirect(url_for('materias.listar'))

	return render_template('materias/criar_materia.html', form=form)


@materias.route('/listar', methods=['POST', 'GET'])
@materias.route('/listar/<id>', methods=['POST', 'GET'])
def listar(id=None):
	if id is None:
		materias = Materia.dbGetAllMateria()
		return render_template('materias/listar_materias.html', materias=materias)
	else:
		materia = Materia.dbGetMateria(id)
		return render_template('materias/detalhes_materia.html', materia=materia)


@materias.route('/atualizar/<id>', methods=['POST', 'GET'])
def atualizar(id):
	form = AtualizarMateriaForm()

	materia = Materia.dbGetMateria(id)

	if form.validate_on_submit():
		materia.dbUpdateMateria(form.nome.data)
		return redirect(url_for('materias.listar'))
	elif request.method == 'GET':
		form.nome.data = materia.nome

	return render_template('materias/atualizar_materia.html', form=form)


@materias.route('/excluir/<id>', methods=['GET'])
def excluir(id):
	Materia.dbDeleteMateria(id)
	return redirect(url_for('materias.listar'))

skoolit/templates/materias/atualizar_materia.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='materias/atualizar_materia.css') }}">
{% endblock %}

{% block title %}Atualizar matéria{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Atualizar matéria</h1>
	</div>

	<div class="card form-materia">
		<div class="card-body">
			<form method="POST">
				{{form.hidden_tag()}}
				{{form.nome.label(class="form-label")}} <br>
				{{form.nome(class="form-control w-50")}} <br>
				{{form.submit(class="btn")}}
			</form>
		</div>
	</div>
</div>

{% endblock %}

skoolit/templates/materias/criar_materia.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='materias/criar_materia.css') }}">
{% endblock %}

{% block title %}Criar matéria{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Criar matéria</h1>
	</div>

	<div class="card form-materia">
		<div class="card-body">
			<form method="POST">
				{{form.hidden_tag()}}
				{{form.nome.label(class="form-label")}} <br>
				{{form.nome(class="form-control w-50")}} <br>
				{{form.submit(class="btn")}}
			</form>
		</div>
	</div>
</div>

{% endblock %}

skoolit/templates/materias/detalhes_materia.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='materias/detalhes_materia.css') }}">
{% endblock %}

{% block title %}{{materia.nome}}{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">{{materia.nome}}</h1>

		<div class="mt-2">
			<a href="{{url_for('materias.atualizar', id=materia.id)}}"
			class="btn mr-2" role="button">
				Editar
			</a>
			<a href="{{url_for('materias.excluir', id=materia.id)}}"
			class="btn" role="button">
				Excluir
			</a>
		</div>
	</div>

		<div class="card descricao-materia">
			<div class="card-body">
				<h5 class="card-title bold"> Descrição da materia</h5>
				<p class="card-text">Mussum Ipsum, cacilds vidis litro abertis. Copo furadis é disculpa de bebadis, arcu quam euismod magna. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis. A ordem dos tratores não altera o pão duris. Cevadis im ampola pa arma uma pindureta.
					Si num tem leite então bota uma pinga aí cumpadi! Mauris nec dolor in eros commodo tempor. Aenean aliquam molestie leo, vitae iaculis nisl. Detraxit consequat et quo num tendi nada. Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.</p>
				<p class="card-text">Mussum Ipsum, cacilds vidis litro abertis. Copo furadis é disculpa de bebadis, arcu quam euismod magna. Nec orci ornare consequat. Praesent lacinia ultrices consectetur. Sed non ipsum felis. A ordem dos tratores não altera o pão duris. Cevadis im ampola pa arma uma pindureta.</p>
			</div>
		</div>

</div>

{% endblock %}

skoolit/templates/materias/listar_materias.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='materias/listar_materias.css') }}">
{% endblock %}

{% block title %}Listar matérias{% endblock %}

{% block content %}

<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Matérias</h1>

		<div class="mt-2">		
			<a href="{{url_for('materias.criar')}}"
				class="btn" role="button">
				Nova matéria
			</a>
		</div>
	</div>
		
	<div class="row">
		{% for materia in materias %}
			<div class="card materia">
				<div class="badge">
					{{materia.nome[:3]|upper}}
				</div>
				<div class="card-body">
					<h5 class="card-title text-center"> 
						<a class="materia-nome" href="{{url_for('materias.listar', id=materia.id)}}">{{materia.nome}}</a>
					</h5>
					<div class="text-center">
						<a href="{{url_for('materias.atualizar', id=materia.id)}}" class="card-link">Editar</a>
						<a href="{{url_for('materias.excluir', id=materia.id)}}" class="card-link">Excluir</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	{% if materias|length == 0  %}
		<p>Não existem matérias criadas.</p>
	{% endif %}
</div>

{% endblock %}