skoolit/views/auth.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for)
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from skoolit import loginManager

#local imports
from skoolit.forms import LoginForm, CriarLoginForm
from skoolit.models import Usuario


auth = Blueprint('auth', __name__, 
				 template_folder='templates', 
				 static_folder='static')

@loginManager.user_loader
def load_user(id):
    return Usuario.dbGetUser(id)

@auth.route('/login', methods=['POST', 'GET'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('home'))
	
	form = LoginForm(request.form)

	if (form.validate_on_submit()):
		usuario = Usuario.dbGetUserNomeEmail(form.nome.data)
		if usuario is None or not usuario.validarSenha(form.senha.data):
			flash('Nome ou senha inválido(s)')
			return redirect(url_for('auth.login'))
		else:
			login_user(usuario, remember=form.rememberme.data)
			# Suporte ao redirecionamento 
			next_page = request.args.get('next')
			if not next_page or url_parse(next_page).netloc != '':
				next_page = url_for('home')
			return redirect(next_page)
			print('Login requisitado pelo usuário {}'.format(form.nome.data))
			return redirect(url_for('home'))

	return render_template('auth/login.html', title='Login', form=form, alert=None)

@auth.route('/criar-login', methods=['POST', 'GET'])
def criarLogin():
	if current_user.is_authenticated:
		return redirect(url_for('home'))
	
	form = CriarLoginForm()
	if form.validate_on_submit():
		novoUsuario = Usuario(form.email.data, 'al', form.nome.data, form.senha.data)
		novoUsuario.dbAddUser()
		return redirect(url_for('auth.login'))
	
	return render_template('auth/criar_login.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('landing'))

skoolit/views/home.py
from flask import render_template, redirect, url_for, g
from flask_login import login_required, current_user

#local imports
from skoolit import app
from skoolit.models import Usuario

@app.route('/home')
@login_required
def home():
	if current_user.papel == 'adm':
		return render_template('home.html') 	#Home do admin
	elif current_user.papel == 'prof':
		return render_template('usuarios/home_prof.html', 
								turmas = current_user.turmas)		#Home do prof
	elif current_user.papel == 'al':
		return render_template('usuarios/home_aluno.html',
								turmas = current_user.turmas)
	else:
		print('Papel de usuário não encontrado!')
		return 404

# Página inicial bonita
@app.route('/')
@app.route('/pagina_inicial')
def landing():
	if(current_user.is_anonymous):
		return render_template('pagina_inicial.html')
 	
	else:
		return redirect(url_for('home'))

skoolit/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<!-- Bootstrap CSS -->
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{{ url_for('static', filename='geral.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='navfoot.css') }}">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	{% block style %}{% endblock %}
	<title>{% block title %}{% endblock %} - Skoolit</title>
	
</head>

<body>
{% block navbar %}{% endblock %}

{% block content %}{% endblock %}

{% block footer %}{% endblock %}
</body>
</html>

skoolit/templates/home.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
{% endblock %}

{% block content %}
<div class="container conteudo">
	<div class="d-flex justify-content-between mb-5">
		<h1 class="bold">Administrar</h1>
	</div>

	<div class="row d-flex justify-content-between align-items-center">
		<div class="card sessao">
			<div class="card-body d-flex justify-content-center align-items-center">
				<h5 class="card-title text-center"> 
					<a class="sessao-nome" href="{{url_for('usuarios.listar')}}">Listagem de usuários</a>
				</h5>
			</div>
		</div>

		<div class="card sessao">
			<div class="card-body d-flex justify-content-center align-items-center">
				<h5 class="card-title text-center"> 
					<a class="sessao-nome" href="{{url_for('turmas.listar')}}">Listagem de turmas</a>
				</h5>
			</div>
		</div>
		
		<div class="card sessao">
			<div class="card-body d-flex justify-content-center align-items-center">
				<h5 class="card-title text-center"> 
					<a class="sessao-nome" href="{{url_for('materias.listar')}}">Listagem de matérias</a>
				</h5>
			</div>
		</div>
	</div>
</div>
{% endblock %}

skoolit/templates/listar.html
{% extends "base.html" %}

{% block title %}Listar usuários{% endblock %}

{% block content %}

<h1>Listar usuários</h1>

<ul>
	{% for usuario in usuarios %}
		<li>{{usuario.email}} | <a href="{{url_for('atualizar', id=usuario.id)}}">Editar</a> | <a href="{{url_for('excluir', id=usuario.id)}}">Excluir</a> |</li>
	{% endfor %}
</ul>

{% if usuarios|length == 0  %}
<p>Não existem tarefas criadas.</p>
{% endif %}

{% endblock %}

skoolit/templates/navfoot.html
{% extends "base.html" %}

{% block navbar %}
<div class="navbar d-flex justify-content-between">
	{% if current_user.is_anonymous %}
		<a href="{{url_for('landing')}}"><img src="{{ url_for('static', filename='logo.svg') }}" alt="logo"></a>
	{% else %}
		<a href="{{url_for('home')}}"><img src="{{ url_for('static', filename='logo.svg') }}" alt="logo"></a>
	{% endif %}
	
	<div class="mt-3">
		{% if request.path != '/' and request.path != '/pagina_inicial' %}
			<div class="d-inline-block">
				{% if current_user.papel == "adm" %}
				<a class="navbar-btn mr-3" role="button" href="{{url_for('usuarios.listar')}}"><b>Usuarios</b></a>
				<a class="navbar-btn mr-3" role="button" href="{{url_for('materias.listar')}}"><b>Materias</b></a>
				<a class="navbar-btn mr-5" role="button" href="{{url_for('turmas.listar')}}"><b>Turmas</b></a>

				{% else %}
				<a class="navbar-btn mr-5" role="button" href="{{url_for('home')}}"><b>Turmas</b></a>
				{% endif %}
			</div>
		{% endif %}
		
		{% if current_user.is_anonymous %}
			{% if request.path != '/pagina_inicial' and request.path != '/' %}
				<a class="navbar-btn mr-3" href="{{url_for('auth.login')}}"><b>Fazer login</b></a>
			{% endif %}		

		{% else %}
			<div  class="dropdown show d-inline-block">

				<p class="mr-3 d-inline-block"><b>{{ current_user.nome }}</b></p>
				<a class="perfil-menu" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<div class="perfil-circulo rounded-circle text-center">
						<b>{{ current_user.nome[0:2].upper()}}</b>
					</div>
				</a>

				<div class="card-menu dropdown-menu mt-2" aria-labelledby="dropdownMenuLink">
					<a class="opcao-menu dropdown-item" href="{{url_for('usuarios.perfil', id=current_user.id)}}">Perfil</a>
					<a class="opcao-menu dropdown-item" href="#">Configuração</a>
					<a class="opcao-menu dropdown-item" href="{{url_for('auth.logout')}}">Sair</a>
				</div>
			</div>
		{% endif %}
	</div>
</div>
{% endblock %}


skoolit/templates/pagina_inicial.html
{% extends "navfoot.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='pagina_inicial.css') }}">
{% endblock %}

{% block content %}
	<div class="d-flex justify-content-between" style="margin-left: 10vh; margin-right: 10vh">
		<div class="d-flex flex-column justify-content-end">	
			<h1><b>Skoolit.</b></h1>
			<h4><b>A reformulação de ser escola</b></h4>
			<p>Uma nova forma de aprender, uma nova maneira de educar</p>

			<div class="d-flex">	
				<a href="{{ url_for('auth.criarLogin') }}" class="btn pl-5 pr-5" style="font-weight: bold" role="button">
					Matricule-se 
				</a>
				<span class="align-self-center ml-2"> 
					ou 
					<a href="{{url_for('auth.login')}}" style="text-decoration: none;">
						<b>entrar</b>
					</a>
				</span>
			</div>
			
		</div>

		<img src="{{ url_for('static', filename='undraw_study.svg') }}" width="50%" height="auto">
	</div>

{% endblock %}